web:
  build: .
  environment:
    MYENV: EXAMPLE
  volumes:
    - .:/code
web_migrate:
  extends:
    service: web
  command: python manage.py migrate research
web_run:
  extends:
    service: web
  command: gunicorn humanscape.wsgi:application --bind 0.0.0.0:8080
  ports:
    - "8080:8080"
